
class Config:
    DIMENSION = 128
    TRESHOLD1 = 0.8
    TRESHOLD2 = 50
    PERCENTAGE = 30
    K = 1
    NODE2VEC_ITERATIONS = 1
    ACO_COARSENING_ITERATIONS = 1
    ALPHA = .5
    NODE2VEC_BATCH_SIZE = 5000
    NODE2VEC_P = 1
    NODE2VEC_Q = 1
    PYRAMID_SCALES = 2
